### ISSUE TITLE
USAGE description requires command while it isn't requirement

### ISSUE THREAD

**Issue by CompuRoot** [vbatts/go-mtree#178]
```
gomtree -h
```

**Returns:**
```
USAGE:
   gomtree [global options] command [command options] [arguments...]
```

where `command` is required argument to `gomtree` while in fact there no functional commands (except `help`) that needed to run `gomtree`

**Suggestion to get rid of :** `command [command options]` at all since it isn't matched upstream and has no functionality in the `gomtree`

----

Also, it might be good to add description (stolen from `MTREE(8)`)  in help section:
```
DESCRIPTION
    The mtree utility compares the file hierarchy rooted in the current
    directory against a specification read from the standard input. Messages
    are written to the standard output for any files whose characteristics
    do not match the specification, or which are missing from either the
    file hierarchy or the specification.
```

**Comment by vbatts** [comment]
the "command" is expected. https://github.com/vbatts/go-mtree/commit/17687d8c29c94d443f970b95700059e61364afac was done so that we could maintain the top-level compatibility, but also begin adding features in subcommands, for specific functionality.
Specifically I want to handle an ordered list of tars that are intended for container image layers, to produce or check that the resulting container image directory hierarchy https://github.com/vbatts/go-mtree/issues/76

**Comment by vbatts** [comment]
I'll open a separate issue for the description.
