### ISSUE TITLE
[RFE] given a manifest, return keywords used

### ISSUE THREAD

**Issue by vbatts** [vbatts/go-mtree#28]
Something like:
```bash
$ gomtree -f ./foo.mtree -list-used
```
to return a parseable string of keywords used, such that subsequent tooling could easily choose to validate the manifest against that set of keywords or less (i.e. ignoring mtimes).

**Comment by stephen679** [comment]
working on this on [739746](https://github.com/stephen679/go-mtree/tree/739746f9042ffbd5dc53b0958bee1d1aafa67b28). I'm wondering if instead of just returning a slice of keywords, we could create something like a `Collector` struct that would output meaningful information about the mtree spec. For example:
```
type Collector struct {
   .
   .
   .
}
ParseSpec(r io.Reader, collectorArgs... ) (*DirectoryHierarchy, *Collector, error) {
}
```
This has no effect on `gomtree`'s functionality, but it might be a nice feature to have, especially when working with mtree files that represent a really large directory.
