### ISSUE TITLE
Time comparison fails on equivalent fractions

### ISSUE THREAD

**Issue by vbatts** [vbatts/go-mtree#8]
```
"var/lib/yum/yumdb/z": keyword "time": expected 1459443788.000000000; got 1459443788.0
```

**Comment by stephen679** [comment]
would an individual check for the "time" keyword in check.go be too ugly? based off of how we actually test the file spec keyval against the actual file, it doesn't seem like string comparison can fully resolve this issue. 

this also brings me to the idea of defining/implementing KeyVal checks for each keyword, so that instead of doing `if string(kv) != curKeyVal`, we can call something along the lines of `checkKeywordFunc(kv,curKeyVal)`. I'm not sure how most KeyVal checks would differ from a string comparison, though, but this would avoid cluttering in check.go and possibly allow for more accurate validation. thoughts?

**Comment by vbatts** [comment]
@stephen679 i think string comparison is fine. The issue here was fairly simple.
